// LUDOK Data
//
// id = xyzi
// where x = #Noxe
//       y = 0 Langzeit, y = 1 Kurzzeit
//       z = #Organ
//       i = #Effekt 
//
// Dr. Carl GmbH 2020
//
// recall: http://alasql.org/
//         https://github.com/agershun/alasql
//
// Vorlage https://www.isglobal.org/en/ciudadesquequeremos#contaminacion
//
// torso scaling: 74%


arrNoxen = [
  {"id": 1,
  "noxe_de": "Feinstaub",
  "noxe_en": "Feinstaub EN",
  "noxe_fr": "Feinstaub FR",
  "noxe_it": "Feinstaub IT",
  },
  {"id": 2,
  "noxe_de": "Ozon",
  "noxe_en": "Ozon EN",
  "noxe_fr": "Ozon FR",
  "noxe_it": "Ozon IT",
  },
  {"id": 3,
  "noxe_de": "Stickstoffdioxid",
  "noxe_en": "Stickstoffdioxid EN",
  "noxe_fr": "Stickstoffdioxid FR",
  "noxe_it": "Stickstoffdioxid IT",
  },
  {"id": 4,
  "noxe_de": "Schwefeldioxid",
  "noxe_en": "Schwefeldioxid EN",
  "noxe_fr": "Schwefeldioxid FR",
  "noxe_it": "Schwefeldioxid IT",
  },
  {"id": 5,
  "noxe_de": "Kohlenmonoxid",
  "noxe_en": "Kohlenmonoxid EN",
  "noxe_fr": "Kohlenmonoxid FR",
  "noxe_it": "Kohlenmonoxid IT",
  }
];


arrOrgane = [
  {"id": 1,
  "organ": "Atemwege",
  "organ_de": "Atemwege",
  "organ_en": "Atemwege EN",
  "organ_fr": "Atemwege FR",
  "organ_it": "Atemwege IT",
  },
  {"id": 2,
  "organ": "Herz",
  "organ_de": "Herz-/Kreislaufsystem",
  "organ_en": "Herz-/Kreislaufsystem EN",
  "organ_fr": "Herz-/Kreislaufsystem FR",
  "organ_it": "Herz-/Kreislaufsystem IT",
  },
  {"id": 3,
  "organ": "Nervensystem",
  "organ_de": "Nervensystem",
  "organ_en": "Nervensystem EN",
  "organ_fr": "Nervensystem FR",
  "organ_it": "Nervensystem IT",
  },
  {"id": 4,
  "organ": "Stoffwechsel",
  "organ_de": "Stoffwechsel/Immunsystem",
  "organ_en": "Stoffwechsel/Immunsystem EN",
  "organ_fr": "Stoffwechsel/Immunsystem FR",
  "organ_it": "Stoffwechsel/Immunsystem IT",
  },
  {"id": 5,
  "organ": "Sterblichkeit",
  "organ_de": "Sterblichkeit",
  "organ_en": "Sterblichkeit EN",
  "organ_fr": "Sterblichkeit FR",
  "organ_it": "Sterblichkeit IT",
  },
  {"id": 6,
  "organ": "Notfälle",
  "organ_de": "Notfälle",
  "organ_en": "Notfälle EN",
  "organ_fr": "Notfälle FR",
  "organ_it": "Notfälle IT",
  }
];


arrEffekte = [
  {"id": 1,
  "effekt_de": "Asthma",
  "effekt_en": "Asthma EN",
  "effekt_fr": "Asthma FR",
  "effekt_it": "Asthma IT",
  "organ": "Atemwege" 
},
{"id": 2,
  "effekt_de": "Atemwegssymptome, z.B. pfeifende Atmung",
  "effekt_en": "",
  "effekt_fr": "",
  "effekt_it": "",
  "organ": "Atemwege"
},
{"id": 3,
  "effekt_de": "Verschlechterung der Erkrankung, mehr Symptome oder Medikation bei Patienten mit Asthma",
  "effekt_en": "",
  "effekt_fr": "",
  "effekt_it": "",
  "organ": "Atemwege"  
},
{"id": 4,
  "effekt_de": "Lungenfunktion verringert bei Patienten mit Asthma",
  "effekt_en": "",
  "effekt_fr": "",
  "effekt_it": "",
  "organ": "Atemwege"  
},
{"id": 5,
  "effekt_de": "Verschlechterung der Erkrankung oder mehr Symptome bei Patienten mit COPD",
  "effekt_en": "",
  "effekt_fr": "",
  "effekt_it": "",
  "organ": "Atemwege"  
},
{"id": 6,
  "effekt_de": "Mehr Symptome bei Allergikern",
  "effekt_en": "",
  "effekt_fr": "",
  "effekt_it": "",
  "organ": "Atemwege"  
},
{"id": 7,
  "effekt_de": "Chronische Bronchitis",
  "effekt_en": "",
  "effekt_fr": "",
  "effekt_it": "",
  "organ": "Atemwege"  
},
{"id": 8,
  "effekt_de": "Lungenfunktion verringert",
  "effekt_en": "",
  "effekt_fr": "",
  "effekt_it": "",
  "organ": "Atemwege"  
},
{"id": 9,
  "effekt_de": "Lungenwachstum verringert",
  "effekt_en": "",
  "effekt_fr": "",
  "effekt_it": "",
  "organ": "Atemwege"  
},
{"id": 10,
  "effekt_de": "Beschleunigte Abnahme der Lungenfunktion",
  "effekt_en": "",
  "effekt_fr": "",
  "effekt_it": "",
  "organ": "Atemwege"  
},
{"id": 11,
  "effekt_de": "Entzündung der Atemwege, entzündliche Reaktion",
  "effekt_en": "",
  "effekt_fr": "",
  "effekt_it": "",
  "organ": "Atemwege"  
},
{"id": 12,
"effekt_de": "Entstehung von Lungenkrebs",
"effekt_en": "",
"effekt_fr": "",
"effekt_it": "",
"organ": "Atemwege"  
},
{"id": 13,
"effekt_de": "Arteriosklerose",
"effekt_en": "",
"effekt_fr": "",
"effekt_it": "",
"organ": "Herz" 
},
{"id": 14,
"effekt_de": "Bluthochdruck",
"effekt_en": "",
"effekt_fr": "",
"effekt_it": "",
"organ": "Herz"  
},
{"id": 15,
"effekt_de": "Herzrhythmusvariabilität",
"effekt_en": "",
"effekt_fr": "",
"effekt_it": "",
"organ": "Herz"  
},
{"id": 16,
"effekt_de": "Blutgerinnung",
"effekt_en": "",
"effekt_fr": "",
"effekt_it": "",
"organ": "Herz"  
},
{"id": 17,
"effekt_de": "Zucker- und Fettstoffwechsel&shy;störungen/-erkrankungen (z.B. Diabetes)",
"effekt_en": "",
"effekt_fr": "",
"effekt_it": "",
"organ": "Stoffwechsel"  
},
{"id": 19,
"effekt_de": "Verringerte Immunabwehr",
"effekt_en": "",
"effekt_fr": "",
"effekt_it": "",
"organ": "Stoffwechsel"  
},
{"id": 20,
"effekt_de": "Gehirnvolumen (Weisse Masse) reduziert",
"effekt_en": "",
"effekt_fr": "",
"effekt_it": "",
"organ": "Nervensystem"  
},
{"id": 21,
"effekt_de": "Abnahme der kognitiven Leistung (Demenz)",
"effekt_en": "",
"effekt_fr": "",
"effekt_it": "",
"organ": "Nervensystem"
},
{"id": 22,
"effekt_de": "Krankheitsbedingte Sterblichkeit",
"effekt_en": "",
"effekt_fr": "",
"effekt_it": "",
"organ": "Sterblichkeit" 
},
{"id": 23,
"effekt_de": "Sterblichkeit wegen Herz-/Kreislaufkrankheiten",
"effekt_en": "",
"effekt_fr": "",
"effekt_it": "",
"organ": "Sterblichkeit"
},
{"id": 24,
"effekt_de": "Sterblichkeit wegen Atemwegserkrankungen",
"effekt_en": "",
"effekt_fr": "",
"effekt_it": "",
"organ": "Sterblichkeit"
},
{"id": 25,
"effekt_de": "Sterblichkeit: Asthma",
"effekt_en": "",
"effekt_fr": "",
"effekt_it": "",
"organ": "Sterblichkeit"
},
{"id": 26,
"effekt_de": "Sterblichkeit: COPD",
"effekt_en": "",
"effekt_fr": "",
"effekt_it": "",
"organ": "Sterblichkeit"
},
{"id": 27,
"effekt_de": "Sterblichkeit: Lungenkrebs",
"effekt_en": "",
"effekt_fr": "",
"effekt_it": "",
"organ": "Sterblichkeit" 
},
{"id": 28,
"effekt_de": "Sterblichkeit: Atemwegsinfektionen",
"effekt_en": "",
"effekt_fr": "",
"effekt_it": "",
"organ": "Sterblichkeit"
},
{"id": 29,
"effekt_de": "Notfälle wegen Atemwegserkrankungen",
"effekt_en": "",
"effekt_fr": "",
"effekt_it": "",
"organ": "Notfälle"
},
{"id": 30,
"effekt_de": "Notfälle wegen Asthma",
"effekt_en": "",
"effekt_fr": "",
"effekt_it": "",
"organ": "Notfälle"
},
{"id": 31,
"effekt_de": "Notfälle wegen COPD",
"effekt_en": "",
"effekt_fr": "",
"effekt_it": "",
"organ": "Notfälle"
},
{"id": 32,
"effekt_de": "Notfälle wegen Herz-/Kreislaufkrankheiten",
"effekt_en": "",
"effekt_fr": "",
"effekt_it": "",
"organ": "Notfälle"
}
];


arrMatrix = [
  {"id": 1011,
  "noxe": "Feinstaub",
  "noxe_zeit": "L",
  "organ": "Atemwege",
  "effekt": "Asthma",
  "effekt_typ": "L"
  },
  {"id": 1012,
  "noxe": "Feinstaub",
  "noxe_zeit": "L",
  "organ": "Atemwege",
  "effekt": "Atemwegssymptome, z.B. pfeifende Atmung",
  "effekt_typ": "L"
  },
  {"id": 1013,
  "noxe": "Feinstaub",
  "noxe_zeit": "L",
  "organ": "Atemwege",
  "effekt": "Verschlechterung der Erkrankung, mehr Symptome oder Medikation bei Patienten mit Asthma",
  "effekt_typ": "L"
  },
  {"id": 1014,
  "noxe": "Feinstaub",
  "noxe_zeit": "L",
  "organ": "Atemwege",
  "effekt": "Lungenwachstum verringert",
  "effekt_typ": "L"
  },
  {"id": 1015,
  "noxe": "Feinstaub",
  "noxe_zeit": "L",
  "organ": "Atemwege",
  "effekt": "Beschleunigte Abnahme der Lungenfunktion",
  "effekt_typ": "L"
  },
  {"id": 1016,
  "noxe": "Feinstaub",
  "noxe_zeit": "L",
  "organ": "Atemwege",
  "effekt": "Entzündung der Atemwege, entzündliche Reaktion",
  "effekt_typ": "L",
  "effekt_zusatz_de": "(Kinder)",
  "effekt_zusatz_en": "(children)",
  "effekt_zusatz_fr": "(l'enfant)",
  "effekt_zusatz_it": "(bambini)"
  },
  {"id": 1017,
  "noxe": "Feinstaub",
  "noxe_zeit": "L",
  "organ": "Atemwege",
  "effekt": "Entstehung von Lungenkrebs",
  "effekt_typ": "L"
  },
  {"id": 1018,
  "noxe": "Feinstaub",
  "noxe_zeit": "L",
  "organ": "Atemwege",
  "effekt": "Lungenfunktion verringert",
  "effekt_typ": "L"
  },

  {"id": 1021,
  "noxe": "Feinstaub",
  "noxe_zeit": "L",
  "organ": "Herz",
  "effekt": "Arteriosklerose",
  "effekt_typ": "C"
  },
  {"id": 1022,
  "noxe": "Feinstaub",
  "noxe_zeit": "L",
  "organ": "Herz",
  "effekt": "Bluthochdruck",
  "effekt_typ": "C"
  },
  {"id": 1023,
  "noxe": "Feinstaub",
  "noxe_zeit": "L",
  "organ": "Herz",
  "effekt": "Herzrhythmusvariabilität",
  "effekt_typ": "C"
  },
  {"id": 1024,
  "noxe": "Feinstaub",
  "noxe_zeit": "L",
  "organ": "Herz",
  "effekt": "Blutgerinnung",
  "effekt_typ": "C"
  },

  {"id": 1031,
  "noxe": "Feinstaub",
  "noxe_zeit": "L",
  "organ": "Nervensystem",
  "effekt": "Gehirnvolumen (Weisse Masse) reduziert",
  "effekt_typ": "L"
  },
  {"id": 1032,
  "noxe": "Feinstaub",
  "noxe_zeit": "L",
  "organ": "Nervensystem",
  "effekt": "Abnahme der kognitiven Leistung (Demenz)",
  "effekt_typ": "L"
  },

  {"id": 1051,
  "noxe": "Feinstaub",
  "noxe_zeit": "L",
  "organ": "Sterblichkeit",
  "effekt": "Krankheitsbedingte Sterblichkeit",
  "effekt_typ": "C"
  },
  {"id": 1052,
  "noxe": "Feinstaub",
  "noxe_zeit": "L",
  "organ": "Sterblichkeit",
  "effekt": "Sterblichkeit wegen Herz-/Kreislaufkrankheiten",
  "effekt_typ": "C"
  },
  {"id": 1053,
  "noxe": "Feinstaub",
  "noxe_zeit": "L",
  "organ": "Sterblichkeit",
  "effekt": "Sterblichkeit wegen Atemwegserkrankungen",
  "effekt_typ": "C",
  "effekt_zusatz_de": "(cardio&shy;pulmonary)",
  "effekt_zusatz_en": "(cardio&shy;pulmonary)",
  "effekt_zusatz_fr": "(cardio&shy;pulmonary)",
  "effekt_zusatz_it": "(cardio&shy;pulmonary)"
  },
  {"id": 1054,
  "noxe": "Feinstaub",
  "noxe_zeit": "L",
  "organ": "Sterblichkeit",
  "effekt": "Sterblichkeit: Asthma",
  "effekt_typ": "L"
  },
  {"id": 1055,
  "noxe": "Feinstaub",
  "noxe_zeit": "L",
  "organ": "Sterblichkeit",
  "effekt": "Sterblichkeit: COPD",
  "effekt_typ": "L"
  },
  {"id": 1056,
  "noxe": "Feinstaub",
  "noxe_zeit": "L",
  "organ": "Sterblichkeit",
  "effekt": "Sterblichkeit: Lungenkrebs",
  "effekt_typ": "C"
  },
  {"id": 1057,
  "noxe": "Feinstaub",
  "noxe_zeit": "L",
  "organ": "Sterblichkeit",
  "effekt": "Sterblichkeit: Atemwegsinfektionen",
  "effekt_typ": "L"
  },

  {"id": 2011,
  "noxe": "Ozon",
  "noxe_zeit": "L",
  "organ": "Atemwege",
  "effekt": "Asthma",
  "effekt_typ": "L"
  },
  {"id": 2012,
  "noxe": "Ozon",
  "noxe_zeit": "L",
  "organ": "Atemwege",
  "effekt": "Verschlechterung der Erkrankung, mehr Symptome oder Medikation bei Patienten mit Asthma",
  "effekt_typ": "L"
  },
  {"id": 2013,
  "noxe": "Ozon",
  "noxe_zeit": "L",
  "organ": "Atemwege",
  "effekt": "Mehr Symptome bei Allergikern",
  "effekt_typ": "L"
  },
  {"id": 2041,
  "noxe": "Ozon",
  "noxe_zeit": "L",
  "organ": "Stoffwechsel",
  "effekt": "Zucker- und Fettstoffwechsel&shy;störungen/-erkrankungen (z.B. Diabetes)",
  "effekt_typ": "L"
  },
  {"id": 2051,
  "noxe": "Ozon",
  "noxe_zeit": "L",
  "organ": "Sterblichkeit",
  "effekt": "Sterblichkeit wegen Atemwegserkrankungen",
  "effekt_typ": "L"
  },
  /*
  {"id": 2061,
  "noxe": "Ozon",
  "noxe_zeit": "L",
  "organ": "Notfälle",
  "effekt": "Notfälle wegen Asthma",
  "effekt_typ": "L"
  },
*/

  {"id": 3011,
  "noxe": "Stickstoffdioxid",
  "noxe_zeit": "L",
  "organ": "Atemwege",
  "effekt": "Asthma",
  "effekt_typ": "L"
  },
  {"id": 3012,
  "noxe": "Stickstoffdioxid",
  "noxe_zeit": "L",
  "organ": "Atemwege",
  "effekt": "Verschlechterung der Erkrankung, mehr Symptome oder Medikation bei Patienten mit Asthma",
  "effekt_typ": "L"
  },
  {"id": 3013,
  "noxe": "Stickstoffdioxid",
  "noxe_zeit": "L",
  "organ": "Atemwege",
  "effekt": "Chronische Bronchitis",
  "effekt_typ": "L"
  },  
  {"id": 3014,
  "noxe": "Stickstoffdioxid",
  "noxe_zeit": "L",
  "organ": "Atemwege",
  "effekt": "Lungenfunktion verringert",
  "effekt_typ": "L"
  },  
  {"id": 3015,
  "noxe": "Stickstoffdioxid",
  "noxe_zeit": "L",
  "organ": "Atemwege",
  "effekt": "Lungenwachstum verringert",
  "effekt_typ": "L"
  },

// Kurzzeit

  {"id": 1111,
  "noxe": "Feinstaub",
  "noxe_zeit": "K",
  "organ": "Atemwege",
  "effekt": "Verschlechterung der Erkrankung, mehr Symptome oder Medikation bei Patienten mit Asthma",
  "effekt_typ": "L"
  },
  {"id": 1112,
  "noxe": "Feinstaub",
  "noxe_zeit": "K",
  "organ": "Atemwege",
  "effekt": "Verschlechterung der Erkrankung oder mehr Symptome bei Patienten mit COPD",
  "effekt_typ": "L"
  },
  {"id": 1113,
  "noxe": "Feinstaub",
  "noxe_zeit": "K",
  "organ": "Atemwege",
  "effekt": "Lungenfunktion verringert",
  "effekt_typ": "L"
  },
  {"id": 1114,
  "noxe": "Feinstaub",
  "noxe_zeit": "K",
  "organ": "Atemwege",
  "effekt": "Entzündung der Atemwege, entzündliche Reaktion",
  "effekt_typ": "L"
  },
  {"id": 1121,
  "noxe": "Feinstaub",
  "noxe_zeit": "K",
  "organ": "Herz",
  "effekt": "Bluthochdruck",
  "effekt_typ": "C"
  },
  {"id": 1122,
  "noxe": "Feinstaub",
  "noxe_zeit": "K",
  "organ": "Herz",
  "effekt": "Herzrhythmusvariabilität",
  "effekt_typ": "C"
  },
  {"id": 1141,
  "noxe": "Feinstaub",
  "noxe_zeit": "K",
  "organ": "Stoffwechsel",
  "effekt": "Verringerte Immunabwehr",
  "effekt_typ": "L"
  },
  {"id": 1151,
  "noxe": "Feinstaub",
  "noxe_zeit": "K",
  "organ": "Sterblichkeit",
  "effekt": "Krankheitsbedingte Sterblichkeit",
  "effekt_typ": "C"
  },
  {"id": 1152,
  "noxe": "Feinstaub",
  "noxe_zeit": "K",
  "organ": "Sterblichkeit",
  "effekt": "Sterblichkeit wegen Herz-/Kreislaufkrankheiten",
  "effekt_typ": "C"
  },
  {"id": 1153,
  "noxe": "Feinstaub",
  "noxe_zeit": "K",
  "organ": "Sterblichkeit",
  "effekt": "Sterblichkeit wegen Atemwegserkrankungen",
  "effekt_typ": "L"
  },
  {"id": 1161,
  "noxe": "Feinstaub",
  "noxe_zeit": "K",
  "organ": "Notfälle",
  "effekt": "Notfälle wegen Atemwegserkrankungen",
  "effekt_typ": "L"
  },
  {"id": 1162,
  "noxe": "Feinstaub",
  "noxe_zeit": "K",
  "organ": "Notfälle",
  "effekt": "Notfälle wegen COPD",
  "effekt_typ": "L"
  },
  {"id": 1163,
  "noxe": "Feinstaub",
  "noxe_zeit": "K",
  "organ": "Notfälle",
  "effekt": "Notfälle wegen Herz-/Kreislaufkrankheiten",
  "effekt_typ": "C"
  },

  {"id": 2111,
  "noxe": "Ozon",
  "noxe_zeit": "K",
  "organ": "Atemwege",
  "effekt": "Atemwegssymptome, z.B. pfeifende Atmung",
  "effekt_typ": "C"
  },
  {"id": 2112,
  "noxe": "Ozon",
  "noxe_zeit": "K",
  "organ": "Atemwege",
  "effekt": "Verschlechterung der Erkrankung, mehr Symptome oder Medikation bei Patienten mit Asthma",
  "effekt_typ": "C"
  },
  {"id": 2113,
  "noxe": "Ozon",
  "noxe_zeit": "K",
  "organ": "Atemwege",
  "effekt": "Lungenfunktion verringert",
  "effekt_typ": "C"
  },
  {"id": 2114,
  "noxe": "Ozon",
  "noxe_zeit": "K",
  "organ": "Atemwege",
  "effekt": "Entzündung der Atemwege, entzündliche Reaktion",
  "effekt_typ": "C"
  },
  {"id": 2141,
  "noxe": "Ozon",
  "noxe_zeit": "K",
  "organ": "Stoffwechsel",
  "effekt": "Zucker- und Fettstoffwechsel&shy;störungen/-erkrankungen (z.B. Diabetes)",
  "effekt_typ": "L"
  },
  {"id": 2161,
  "noxe": "Ozon",
  "noxe_zeit": "K",
  "organ": "Notfälle",
  "effekt": "Notfälle wegen Atemwegserkrankungen",
  "effekt_typ": "C"
  },
  {"id": 2162,
  "noxe": "Ozon",
  "noxe_zeit": "K",
  "organ": "Notfälle",
  "effekt": "Notfälle wegen Asthma",
  "effekt_typ": "C"
  },
  {"id": 2163,
  "noxe": "Ozon",
  "noxe_zeit": "K",
  "organ": "Notfälle",
  "effekt": "Notfälle wegen COPD",
  "effekt_typ": "C"
  },

  {"id": 3111,
  "noxe": "Stickstoffdioxid",
  "noxe_zeit": "K",
  "organ": "Atemwege",
  "effekt": "Atemwegssymptome, z.B. pfeifende Atmung",
  "effekt_typ": "C"
  },
  {"id": 3112,
  "noxe": "Stickstoffdioxid",
  "noxe_zeit": "K",
  "organ": "Atemwege",
  "effekt": "Verschlechterung der Erkrankung, mehr Symptome oder Medikation bei Patienten mit Asthma",
  "effekt_typ": "C"
  },
  {"id": 3113,
  "noxe": "Stickstoffdioxid",
  "noxe_zeit": "K",
  "organ": "Atemwege",
  "effekt": "Lungenfunktion verringert bei Patienten mit Asthma",
  "effekt_typ": "C"
  },
  {"id": 3151,
  "noxe": "Stickstoffdioxid",
  "noxe_zeit": "K",
  "organ": "Sterblichkeit",
  "effekt": "Sterblichkeit wegen Atemwegserkrankungen",
  "effekt_typ": "C"
  },
  {"id": 3161,
  "noxe": "Stickstoffdioxid",
  "noxe_zeit": "K",
  "organ": "Notfälle",
  "effekt": "Notfälle wegen Asthma",
  "effekt_typ": "C"
  },

  {"id": 4111,
  "noxe": "Schwefeldioxid",
  "noxe_zeit": "K",
  "organ": "Atemwege",
  "effekt": "Verschlechterung der Erkrankung, mehr Symptome oder Medikation bei Patienten mit Asthma",
  "effekt_typ": "C"
  },
  {"id": 4112,
  "noxe": "Schwefeldioxid",
  "noxe_zeit": "K",
  "organ": "Atemwege",
  "effekt": "Lungenfunktion verringert bei Patienten mit Asthma",
  "effekt_typ": "C"
  },
  {"id": 4113,
  "noxe": "Schwefeldioxid",
  "noxe_zeit": "K",
  "organ": "Atemwege",
  "effekt": "Lungenfunktion verringert",
  "effekt_typ": "C",
  "effekt_zusatz_de": "(Empfindliche)",
  "effekt_zusatz_en": "()",
  "effekt_zusatz_fr": "()",
  "effekt_zusatz_it": "()"
  },
  {"id": 4151,
  "noxe": "Schwefeldioxid",
  "noxe_zeit": "K",
  "organ": "Sterblichkeit",
  "effekt": "Sterblichkeit wegen Atemwegserkrankungen",
  "effekt_typ": "C"
  },
  {"id": 4161,
  "noxe": "Schwefeldioxid",
  "noxe_zeit": "K",
  "organ": "Notfälle",
  "effekt": "Notfälle wegen Asthma",
  "effekt_typ": "C",
  "effekt_zusatz_de": "(Kinder, 65+)",
  "effekt_zusatz_en": "()",
  "effekt_zusatz_fr": "()",
  "effekt_zusatz_it": "()"
  },

  {"id": 5161,
  "noxe": "Kohlenmonoxid",
  "noxe_zeit": "K",
  "organ": "Notfälle",
  "effekt": "Notfälle wegen Herz-/Kreislaufkrankheiten",
  "effekt_typ": "L"
  }

  ];


